version: '3'

services:
  app:
    build: .
    ports:
      - '8080:8080'
    depends_on:
      - redis
    restart: on-failure

  redis:
    image: 'redis/redis-stack'
    ports:
      - '8001:8001'
    restart: on-failure