version: '3'

services:
  app:
    build: .
    environment:
      - MAIL_USER=MAIL_USER
      - MAIL_PASSWORD=MAIL_PASSWORD
      - ORIGIN_URI=https://museum-admin-weld.vercel.app
    ports:
      - '8080:8080'
    depends_on:
      - redis
    restart: on-failure

  redis:
    image: 'redis/redis-stack:7.2.0-v0'
    ports:
      - '8001:8001'
    restart: on-failure