version: '3'

services:
  app:
    build: .
    ports:
      - '8080:8080'
    environment:
      MAIL_USER: ${MAIL_USER}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
    depends_on:
      - redis
    restart: on-failure

  redis:
    image: 'redis/redis-stack'
    ports:
      - '8001:8001'
    restart: on-failure